Refactor and update to Sphinx 1.8.1 (without PDF)

diff --git a/files/usr/local/bin/sphinx-init b/files/usr/local/bin/sphinx-init
--- a/files/usr/local/bin/sphinx-init
+++ b/files/usr/local/bin/sphinx-init
@@ -1,32 +1,72 @@
 #!/bin/bash
 
-# ----- Generate skeleton ------------------------------------------------------
+source /usr/share/ddidier/bash_colours
 
+SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+
+function sphinx_init_log() {
+    echo -e "${BOLD_YELLOW}[sphinx-init] $1 ${TXT_RESET}"
+}
+
+# ---------------------------------------- Generate documentation skeleton -----
+
+sphinx_init_log "Generating documentation skeleton"
 sphinx-quickstart --makefile --no-batchfile "$@"
 
-# ----- Add 'livehtml' and 'pdf' builders to Makefile --------------------------
+# ----------------------------- Find where is located the source directory -----
+
+if [ -f "$DATA_DIR/conf.py" ]; then
+    source_dir="$DATA_DIR"
+elif [ -f "$DATA_DIR/source/conf.py" ]; then
+    source_dir="$DATA_DIR/source"
+else
+    echo -e "${BOLD_RED}"
+    echo -e " ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓"
+    echo -e " ┃ ERROR: cannot find the file 'conf.py' in the directories                  ┃"
+    echo -e " ┃        /doc and /doc/source                                               ┃"
+    echo -e " ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛"
+    echo -e "${TXT_RESET}"
+    exit 1
+fi
+
+# ----------------------------------------------------- Customize Makefile -----
+
+sphinx_init_log "Customizing Makefile"
 
 makefile="$DATA_DIR/Makefile"
 
-touch "$makefile"
+sphinx_init_log "  - Copying '$makefile' to '$makefile.bak'"
+cp -n $makefile $makefile.bak
 
-echo    ""                                                                              >> "$makefile"
-echo    "livehtml:"                                                                     >> "$makefile"
-echo -e "\tsphinx-autobuild -b html --host 0.0.0.0 \$(ALLSPHINXOPTS) \$(BUILDDIR)/html" >> "$makefile"
-echo    ""                                                                              >> "$makefile"
-echo    "pdf:"                                                                          >> "$makefile"
-echo -e "\t\$(SPHINXBUILD) -b pdf \$(ALLSPHINXOPTS) \$(BUILDDIR)/pdf"                   >> "$makefile"
-echo -e "\t@echo"                                                                       >> "$makefile"
-echo -e "\t@echo \"Build finished. The PDF files are in \$(BUILDDIR)/pdf.\""            >> "$makefile"
+sphinx_init_log "  - Adding 'livehtml' target to Makefile"
+echo -e ""                                                                                                      >> "$makefile"
+echo -e ""                                                                                                      >> "$makefile"
+echo -e "livehtml:"                                                                                             >> "$makefile"
+echo -e "\tsphinx-autobuild -b html --host 0.0.0.0 \$(ALLSPHINXOPTS) \"\$(SOURCEDIR)\" \"\$(BUILDDIR)/html\""   >> "$makefile"
 
-# ----- Add PDF extension to configuration -------------------------------------
+# ------------------------------------------------ Customize configuration -----
 
-configuration="$DATA_DIR/conf.py"
+sphinx_init_log "Customizing configuration"
 
-if [ ! -f "$configuration" ]; then
-    configuration="$DATA_DIR/source/conf.py"
-fi
+configuration_file=$source_dir/conf.py
 
-sed -i -e "s/^extensions = \[\]/extensions = [\'rst2pdf.pdfbuilder\']/g" "$configuration"
+sphinx_init_log "  - Copying '$configuration_file' to '$configuration_file.bak'"
+cp -n $configuration_file $configuration_file.bak
 
-cat "/usr/local/bin/sphinx-init-conf.py" >> "$configuration"
+sphinx_init_log "  - Adding extensions"
+sphinx_init_log "  - Enabling Markdown"
+sphinx_init_log "  - Enabling TODOs"
+
+cat $SCRIPT_DIR/sphinx-init-conf.py >> $configuration_file
+
+# ----------------------------------------------------- Add some resources -----
+
+site_packages_dir=/usr/local/lib/python2.7/site-packages
+
+sphinx_init_log "Adding resources"
+
+sphinx_init_log "  - Adding 'sphinxcontrib-excel-table' resources"
+excel_table_dir=$site_packages_dir/sphinxcontrib/excel_table
+cp -n $excel_table_dir/resources/_templates/layout.html            $source_dir/_templates/
+cp -n $excel_table_dir/resources/_static/handsontable.full.min.js  $source_dir/_static/
+cp -n $excel_table_dir/resources/_static/handsontable.full.min.css $source_dir/_static/
